sudo: required

services:
  - docker

install: true

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t $NAME:$VERSION .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag $NAME:$VERSION $NAME:$VERSION && docker push $NAME:$VERSION;
    fi
